---
title: "Lab 6 Report"
author: "Ben Peters"
output: html_document
bibliography: lab_6_ref.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Ben's COVID-19 Report
```{r, echo = FALSE, include=FALSE}
library(tidyverse)
library(maps)
library(mapdata)
library(lubridate)
library(viridis)
library(wesanderson)
library(DT)
library(RColorBrewer)
```
```{r, echo = FALSE, message=FALSE}
todays_report <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/10-06-2020.csv")) %>% 
  rename(Long = "Long_")
```
```{r, echo = FALSE, fig.width=10, fig.align='center', warning=FALSE}
ggplot(todays_report, aes(x = Long, y = Lat, size = Confirmed/100000)) +
    borders("world", colour = NA, fill = "grey90") +
    theme_bw() +
    geom_point(shape = 21, color='purple', fill='red', alpha = 0.2) +
    labs(title = 'World Distribution of COVID-19 Confirmed cases',x = '', y = '',
        size="Cases (x100000))") +
    theme(legend.position = "right") +
    theme_void() +
    coord_fixed(ratio=1.3)
```


## COVID-19 in the United States
```{r, echo=FALSE,warning=FALSE, fig.align='center', fig.width=12}
tr_na <- todays_report %>% 
  filter(Country_Region == "US") %>% 
  filter (!Province_State %in% c("Alaska","Hawaii","American Samoa",
                  "Puerto Rico","Northern Mariana Islands", 
                  "Virgin Islands", "Recovered", "Guam", "Grand Princess",
                  "Diamond Princess")) %>% 
  filter(Lat > 0)

mybreaks <- c(1, 100, 1000, 10000, 50000, 100000)
ggplot(tr_na, aes(x = Long, y = Lat, size = Confirmed)) +
    borders("state", colour = "white", fill = "grey90") +
    geom_point(aes(x=Long, y=Lat, size=Confirmed, color=Confirmed),stroke=F, alpha=0.5) +
    scale_size_continuous(name="Cases", range=c(1,20), 
                        breaks=mybreaks, labels = c("1-99",
                        "100-999", "1,000-9,999", "10,000-49,999","50,000-99,999", "100,000+")) +
    scale_color_viridis_c(option="plasma",name="Cases",
                        trans="log", breaks=mybreaks, labels = c("1-99",
                        "100-999", "1,000-9,999", "10,000-49,999","50,000-99,999", "100,000+"))  +
  
  theme_void() + 
    guides( colour = guide_legend()) +
    labs(title = "Distribution of Confirmed COVID-19 Cases in the Lower 48") +
    theme(
      legend.position = "right",
      text = element_text(color = "#22211d"),
      plot.background = element_rect(fill = "#ffffff", color = NA), 
      panel.background = element_rect(fill = "#ffffff", color = NA), 
      legend.background = element_rect(fill = "#ffffff", color = NA)
    ) +
    coord_fixed(ratio=1.5)
```

Interactive! Hover over state for exact number
```{r, echo=FALSE, message=FALSE, fig.width=12, fig.align='center', warning=FALSE}
tr_us <- todays_report %>% 
  filter(Country_Region == "US") %>% 
  group_by(Province_State) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  mutate(Province_State = tolower(Province_State))

us <- map_data("state")

state_join <- left_join(us, tr_us, by = c("region" = "Province_State"))

# ggplot(data = us, mapping = aes(x = long, y = lat, group = group)) + 
#   coord_fixed(1.3) + 
# 
#   geom_polygon(data = state_join, aes(fill = Confirmed), color = "white") +
#   scale_fill_gradientn(colors = brewer.pal(n = 6, name = "Reds"),
#                        trans = "log10", na.value = "White") +
#   labs(title = "COVID-19 Confirmed Cases in the US by State") +
#   theme_void()
library(plotly)
 ggplotly(
   ggplot(data = us, mapping = aes(x = long, y = lat, group = group)) +
   coord_fixed(1.3) +

   geom_polygon(data = state_join, aes(fill = Confirmed), color = "white") +
    scale_fill_gradientn(colors = brewer.pal(n = 6, name = "Reds"),
                         na.value = "White") +
   ggtitle("COVID-19 Cases by US State") +
   labs(x=NULL, y=NULL) +
   theme(panel.border = element_blank()) +
   theme(panel.background = element_blank()) +
   theme(axis.ticks = element_blank()) +
   theme(axis.text = element_blank())
 )
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
tr_county <- todays_report %>% 
  unite(Key, Admin2, Province_State, sep = ".") %>% 
  group_by(Key) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  mutate(Key = tolower(Key))

us <- map_data("state")
counties <- map_data("county") %>% 
  unite(Key, subregion, region, sep = ".", remove = FALSE)


```
```{r, echo = FALSE, warning=FALSE, fig.align='center', fig.width=12}
county_join <- left_join(counties, tr_county, by = c("Key"))
ggplot(data = us, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  borders("state", colour = "black") +
  geom_polygon(data = county_join, aes(fill = Confirmed)) +
  scale_fill_gradientn(colors = brewer.pal(n = 6, name = "Reds"),
                       breaks = c(1, 10, 100, 1000, 10000, 100000),
                       trans = "log10", na.value = "White") +
  ggtitle("Number of Confirmed Cases by US County") +
  theme_void() 
```


## COVID-19 in MA
Interactive! Hover over county for case numbers.
```{r, echo=FALSE, message=FALSE, fig.align='center', fig.width=10, warning=FALSE}
ma_report <- todays_report %>% 
  filter(Province_State == "Massachusetts") %>% 
  group_by(Admin2) %>% 
  summarize(Confirmed = sum(Confirmed)) %>% 
  mutate(Admin2 = tolower(Admin2))
us <- map_data("state")
ma_us <- subset(us, region == "massachusetts")
counties <- map_data("county")
ma_county <- subset(counties, region == "massachusetts")
ma_join <- left_join(ma_county, ma_report, by = c("subregion" = "Admin2")) 

ggplotly(
ggplot(data = ma_county, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(data = ma_join, aes(fill = Confirmed), color = "white") +
    scale_fill_gradientn(colors = brewer.pal(n = 5, name = "Reds")) +
  labs(title = "COVID-19 Confirmed Cases in Massachusetts") +
  theme_void()
)
```

Application written in R [@RCoreTeam]

All data from John's Hopkins University COVID-19 Dashboard and Repository [@JHU_COVID_Data]

## References