---
title: "Lab 3B"
author: "Ben Peters"
date: "September 13, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
surveys <- read_csv("data/portal_data_joined.csv")
```

```{r}
str(surveys)
```

```{r}
view(surveys)
```
```{r}
select(surveys, plot_id, species_id, weight)
```
```{r}
select(surveys, -record_id, -species_id)
```

```{r}
filter(surveys, year == 1995)
```
```{r}
surveys2 <- filter(surveys, weight < 5)
surveys_sml <- select(surveys2, species_id, sex, weight)
```
```{r}
surveys_sml <- select(filter(surveys, weight < 5), species_id, sex, weight)
```
```{r}
surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)
```

## Challenge
```{r}
surveys %>%
  filter(year < 1995) %>% 
  select(year, sex, weight)
```

```{r}
surveys %>%
  mutate(weight_kg = weight / 1000,
         weight_lb = weight_kg * 2.2)
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  mutate(weight_kg = weight / 1000) %>%
  head()
```

## Challenge
```{r}
surveys_metric_hindfoot <- surveys %>% 
  filter(!is.na(hindfoot_length)) %>%
  mutate(hindfoot_cm = hindfoot_length / 10) %>%
  filter(hindfoot_cm < 3) %>%
  select(species_id, hindfoot_cm)
head(surveys_metric_hindfoot)
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight)) %>% 
  print(n = 15)
```

```{r}
surveys %>%
  count(sex, species) %>%
  arrange(species, desc(n))
```

## Challenge
1.
```{r}
surveys %>% 
  count(plot_type)
```

2.
```{r}
surveys %>%
    filter(!is.na(hindfoot_length)) %>%
    group_by(species_id) %>%
    summarize(
        mean_hf_length = mean(hindfoot_length),
        min_hf_length = min(hindfoot_length),
        max_hf_length = max(hindfoot_length),
        n = n()
    )
```

3. 
```{r}
surveys %>%
    filter(!is.na(weight)) %>%
    group_by(year) %>%
    filter(weight == max(weight)) %>%
    select(weight, genus, species_id, year)
```


```{r}
surveys_gw <- surveys %>%
  filter(!is.na(weight)) %>%
  group_by(plot_id, genus) %>%
  summarize(mean_weight = mean(weight))
```


```{r}
surveys_spread <- surveys_gw %>%
  spread(key = genus, value = mean_weight)

str(surveys_spread)
```


```{r}
surveys_gather <- surveys_spread %>%
  gather(key = "genus", value = "mean_weight", -plot_id)

str(surveys_gather)
```

## Challenge
1.
```{r}
surveys_spread_gen <- surveys %>% 
  group_by(plot_id, year) %>%
  summarize(n_genera = n_distinct(genus)) %>%
  spread(year, n_genera)
head(surveys_spread_gen)
```

2. 
```{r}
surveys_spread_gen %>% 
  gather("year", "n_genera", -plot_id)
```

3.
```{r}
surveys_measurement <- surveys %>%
  gather("measurement", "value", hindfoot_length, weight)
head(surveys_measurement)
```

4.
```{r}
surveys_measurement %>% 
  group_by(year, measurement, plot_type) %>% 
  summarize(mean_value = mean(value, na.rm = TRUE)) %>% 
  spread(measurement, mean_value)
```



```{r}
surveys_complete <- surveys %>%
  filter(!is.na(weight),
         !is.na(hindfoot_length),
         !is.na(sex))
```
```{r}
species_counts <- surveys_complete %>%
    count(species_id) %>% 
    filter(n >= 50)

surveys_complete <- surveys_complete %>%
  filter(species_id %in% species_counts$species_id)
```

```{r}
write_csv(surveys_complete, path = "data/surveys_complete.csv")
```




