---
title: "Lab 9x"
author: "Ben Peters"
date: "November 16, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
x <- runif(1, 0, 10)  
if(x > 5) {
        y <- 1
} else {
        y <- 0
}
y
```

```{r}
for(i in 1:12) {
        print(i)
}
```
```{r}
x <- c("apple", "broccoli", "carrot", "dill", "eggplant", "fennel")
## was a bit hungry while making this
for(i in 1:6) {
        print(x[i])  
}
```
```{r}
for(i in seq_along(x)) {   
        print(x[i])
}
```
```{r}
for(letter in x) {
        print(letter)
}
```
```{r}
for(i in 1:6) print(x[i])
```
```{r}
x <- matrix(1:6, 2, 3)
for(i in seq_len(nrow(x))) {
        for(j in seq_len(ncol(x))) {
                print(x[i, j])
        }   
}
```
```{r}
count <- 0
while(count < 10) {
        print(count)
        count <- count + 1
}
```
```{r}
z <- 5
set.seed(1)
while(z >= 3 && z <= 10) {
        coin <- rbinom(1, 1, 0.5)
        
        if(coin == 1) {
                z <- z + 1
        } else {
                z <- z - 1
        } 
}
print(z)
```
```{r}
f <- function() {
        cat("I definitely know what I'm doing")
}
f()
```
```{r}
ashiningexample <- function(num) {
        for(i in seq_len(num)) {
                cat("All work and no play makes Jack a dull boy. ")
        }
}
ashiningexample(10)
```
```{r}
f <- function(num) {
        tragic <- "Have you ever heard the tragedy of Darth Plagueis the Wise? "
        for(i in seq_len(num)) {
                cat(tragic)
        }
        chars <- nchar(tragic) * num
        chars
}
anothermoviereference <- f(3)

if(anothermoviereference == 177){
  print("I thought not, it's not a story the Jedi would tell you.")
}
```

```{r}
f <- function(num = 1) {
        hello <- "One is the loneliest number "
        for(i in seq_len(num)) {
                cat(hello)
        }
        chars <- nchar(hello) * num
        chars
}
f()
```
```{r}
f(2)
```
```{r}
f(num = 2)
```



